<?php
require_once('Middleware.php');

class RoleCheckMiddleware extends Middleware
{
    /**
     * Checking the user role
     * @param $email
     * @param $password
     * @return bool
     */
    public function check($email, $password)
    {
        if ($email === 'admin@example.com'){
            echo "RoleCheckMiddleware: Welcome mister Admin\n";
            return true;
        }
        echo "RoleCheckMiddleware: Hello, user!\n";
        return parent::check($email, $password); // TODO: Change the autogenerated stub
    }
}